/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import type { Route as _IndexRoute } from './pages/';
import type { Route as _NotificationsRoute } from './pages/notifications';
import type { Route as _PostIdRoute } from './pages/post/[id]';
import type { Route as _SettingsRoute } from './pages/settings';
import type { Route as _WriteRoute } from './pages/write';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/write': (typeof _WriteRoute)['_inputType'];
    '/post/:id': (typeof _PostIdRoute)['_inputType'];
    '/notifications': (typeof _NotificationsRoute)['_inputType'];
    '/settings': (typeof _SettingsRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/write': (typeof _WriteRoute)['_outputType'];
    '/post/:id': (typeof _PostIdRoute)['_outputType'];
    '/notifications': (typeof _NotificationsRoute)['_outputType'];
    '/settings': (typeof _SettingsRoute)['_outputType'];
  }
}
